---
dev_addr: "0.0.0.0:8002"
site_name: "Nornir Nautobot Documentation"
site_url: "https://nornir-nautobot.readthedocs.io"
repo_url: "https://github.com/nautobot/nornir-nautobot"
copyright: "Copyright &copy; Network To Code"
theme:
  name: "material"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "navigation.tracking"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.indexes"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
  favicon: "assets/favicon.ico"
  logo: "assets/nautobot_logo.svg"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: "default"
      primary: "black"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      primary: "black"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
extra_css:
  - "assets/extra.css"

extra:
  generator: true

markdown_extensions:
  - "admonition"
  - "toc":
      permalink: true
  - "attr_list"
  - "md_in_html"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "footnotes"
plugins:
  - "search"
  - "mkdocs-version-annotations"

nav:
  - Overview: "index.md"
  - Inventory:
      - Inventory Overview: "inventory/inventory.md"
      - Common Issues: "inventory/common_issues.md"
  - Processor Plugin: "processor/processor.md"
  - Task Plugin: "task/task.md"
  - Developer Guide:
      - Contributing: "dev/CONTRIBUTING.md"
      - Changelog: "dev/CHANGELOG.md"
  - Nautobot Docs Home ↗︎: "https://docs.nautobot.com/"
