---
name: "CI"
on:
  - "push"
jobs:
  lint:
    env:
      INVOKE_LOCAL: "True"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Linting"
        run: "pip install --upgrade pip wheel invoke toml black bandit pydocstyle flake8 yamllint"
      - name: "Linting: Black"
        run: "invoke black"
      - name: "Linting: Bandit"
        run: "invoke bandit"
      - name: "Linting: pydocstyle"
        run: "invoke pydocstyle"
      - name: "Linting: flake8"
        run: "invoke flake8"
      - name: "Linting: yamllint"
        run: "invoke yamllint"
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Setup"
        run: "pip install invoke poetry toml"
      - name: "Build Container"
        run: "invoke build"
    needs:
      - "lint"
  pylint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Linting"
        run: "pip install invoke poetry toml"
      - name: "Build Container"
        run: "invoke build"
      - name: "Linting: Pylint"
        run: "invoke pylint"
    needs:
      - "lint"
      - "build"
  pytest:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Linting"
        run: "pip install invoke poetry toml"
        env:
          PYTHON_VER: "${{ matrix.python-version }}"
      - name: "Build Container"
        run: "invoke build"
        env:
          PYTHON_VER: "${{ matrix.python-version }}"
      - name: "Run Tests"
        run: "invoke pytest"
        env:
          PYTHON_VER: "${{ matrix.python-version }}"
    needs:
      - "lint"
      - "build"
      - "pylint"
  publish_gh:
    name: "Publish to GitHub"
    runs-on: "ubuntu-20.04"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Linting"
        run: "pip install invoke poetry toml"
      - name: "Set env"
        run: "echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Upload binaries to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.NTC_GITHUB_TOKEN }}"
          file: "dist/*"
          tag: "${{ github.ref }}"
          overwrite: true
          file_glob: true
    needs:
      - "lint"
      - "build"
      - "pylint"
      - "pytest"
  publish_pypi:
    name: "Push Package to PyPI"
    runs-on: "ubuntu-20.04"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Push to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          user: "__token__"
          password: "${{ secrets.PYPI_API_TOKEN }}"
    needs:
      - "lint"
      - "build"
      - "pylint"
      - "pytest"
